version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_api_product
      MYSQ_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-databasemysql:/var/lib/mysql
volumes:
  my-databasemysql:
